const path = require('path')
console.log(path.sep)
const filePath = path.join('/tutoNode','test','test.txt')
console.log(`file Path : ${filePath} `)
const base = path.basename(filePath)
console.log(base)
const absolute = path.resolve(__dirname,'tutoNode','test','text.txt')
console.log(absolute)
